name: Update master image

on:
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:

env:
  TAG: latest
  BRANCH: master-deploy
  PACKAGE_NAME: placeholder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # Prepare .github/Dockerfile for slim Sage image

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Prepare Package Name
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          SAGE_VERSION=$(curl -s "https://archlinux.org/packages/search/json/?name=sagemath" | jq -r '.results[0].pkgver')
          PACKAGE_NAME=ghcr.io/${{ github.repository }}:${SAGE_VERSION}
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .github
          push: true
          tags: ${{ env.PACKAGE_NAME }}

      # Update files for Binder

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - name: Update files for Binder
        run: |
          PACKAGE_NAME=${{ env.PACKAGE_NAME }}
          PACKAGE_NAME_ESCAPED=$(echo "${PACKAGE_NAME}" | sed 's/\//\\\//g')
          sed -i "s/FROM \S*/FROM ${PACKAGE_NAME_ESCAPED}/g" Dockerfile
          sed -i "s/FROM \S*/FROM ${PACKAGE_NAME_ESCAPED}/g" README.rst
          git config --global user.email alice@wonderland
          git config --global user.name alice
          git commit -a --amend -m "Update files for Binder"
          git push -f origin $BRANCH

      # Build docker image for Binder from Dockerfile at root

      - name: Binder build
        timeout-minutes: 30
        continue-on-error: true
        run: |
          curl --keepalive-time 600 -L https://mybinder.org/build/gh/KRACK-BIT/sage-binder-env/$BRANCH
